# Generated by Django 3.0.8 on 2020-09-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20200903_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='default', max_length=255, verbose_name='username'),
        ),
    ]
